### ISSUE TITLE
Which programming languages are supported?

### ISSUE THREAD

**Issue by ymotongpoo** [tk0miya/sphinxcontrib-codeblock-callouts#1]
When I tried this extension with Go source code, the code block was not properly parsed, maybe because of the callout comments such as `#1`

I used the following Go code:

```reST
.. code-block:: go
   :name: sample1
   :caption: sample code for callout

   func main() {
       Foo() #1
   }
```

Then I got:

```
WARNING: Could not lex literal_block as "go". Highlighting skipped.
```

**Comment by ymotongpoo** [comment]
Is this regexp line the cause of the issue?
https://github.com/tk0miya/sphinxcontrib-codeblock-callouts/blob/main/sphinxcontrib/codeblock/callouts/__init__.py#L52-L53

Is it possible to replace this `#` with the comment notation of the language in concern?

**Comment by SilverRainZ** [comment]
It is a better idea to use the comment notation according to the language, just an example:

```py
def get_line_comment_mark(language: str) -> str | None:
    table = [
        ('#', ['python', 'py',
               'bash', 'sh', 'ksh', 'zsh', 'shell', 'console', 'shell-session',
               'yaml', 'yml', 'toml',
               'nginx', 'ini', 'cfg', 'pacmanconf',
               'make', 'makefile', 'meson', 'cmake',
               'docker', 'dockerfile',
               ]),

        ('//', ['c', 'cpp', 'csharp', 'c#', 'cs',
                'golang', 'go',
                'rust', 'rs',
                'javascript', 'js', 'typescript', 'ts', 'json',
                'zig',
                ]),

        ('--', ['lua', 'haskell', 'hs']),

        ('"', ['vim']),

        ('::', ['bat', 'batch']),
    ]

    for mark, langs in table:
        if language in langs:
            return 
```

**Comment by tk0miya** [comment]
Now I added JS style comment (starts with `//`).

**Comment by tk0miya** [comment]
@SilverRainZ thank you for your comment. But there is no way to get the language of the code-block from the pygments formatter. It would be better to support more comment styles. Please send me a PR if you have another idea. Thanks.
